version: "3"

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: featurestore-proxy
    networks:
      - frontend-network
      - backend-network
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - frontend

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./source/front
    container_name: frontend
    networks:
      - frontend-network
      - backend-network
    hostname: frontend
    volumes:
      - /app/node_modules
      - ./source/front/:/app
    ports:
      - "3000:3000" # port 맵핑
    stdin_open: true

  backend:
    build:
      context: ./source/back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: backend
    hostname: backend
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://featurestore-mysql.verda-cmp.jp2-dev.db.line-apps-dev.com:20306/FEATURE_STORE?useUnicode=true&charaterEncoding=utf-8&serverTimezone=Asia/Seoul",
        "spring.datasource.username" : "www",
        "spring.datasource.password" : "featurestore0513",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect"
      }'
    networks:
      - backend-network
      - frontend-network