apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: featurestore
spec:
  cassandra:
    serverVersion: "4.0.1"
    datacenters:
      - metadata:
          name: dc1
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: "ssd-nova"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 25Gi
        config:
          jvmOptions:
            heapSize: 512M
        stargate:
          size: 1
          heapSize: 256M
